#!/usr/bin/bash

# ------------------------------------------------------------------
#title           :install.sh
#description     :This script installs my linux configuration.
#author          :fadi haddad
#date            :02 jan 2020
#version         :0.1
#usage           :bash install.sh
#notes           :dont need root access.
#-------------------------------------------------------------------

__check_installed(){
    hash $1 2>/dev/null
    [[ $? -eq 1 ]] && {
        echo $1 "is not installed on your system."
        echo "Skipping this component, moving to the next"
        return 1
    }
    return 0
}

__make_link(){
    conf_file=$(basename $1)
    [[ -e $HOME/$conf_file ]] && {
        echo "$conf_file already exists"
        echo "creating backup"
        mv $HOME/$conf_file $HOME/$conf_file"_bckup"
    }
    [[ -h $HOME/$conf_file ]] && rm $HOME/$conf_file
    ln -s $1 $HOME/$conf_file
    return 0
}

usage="${0##*/} -- [-h --help]
    install dotfiles to home directory by creating symbolic links"

abs_path=$(dirname $(realpath $0))
while getopts ':hgbvstz' option; do
    case "$option" in
        h|help)
            echo -e "$usage" >&2
            exit 1
            ;;
        b)
            __make_link $abs_path/.bashrc
            ;;
        g)
            __check_installed git
            [[ $? -eq 0 ]] && __make_link $abs_path/.gitconfig
            ;;
        s)
            __check_installed screen
            [[ $? -eq 0 ]] && __make_link $abs_path/.screenrc
            ;;
        t)
            __check_installed tmux
            [[ $? -eq 0 ]] && __make_link $abs_path/.tmux.conf
            ;;
        v)
            __check_installed vim
            [[ $? -eq 0 ]] && __make_link $abs_path/.vimrc
            ;;
        p)
            __check_installed zathura
            [[ $? -eq 0 ]] && __make_link $abs_path/.zathurarc
            ;;
        z)
            __check_installed zsh
            [[ $? -eq 0 ]] && __make_link $abs_path/.zshrc
            ;;
        *)
            echo -e " Please launch ${0##*/} -h or --help to show the script usage"
            exit 1
            ;;
    esac
done

shift $(($OPTIND -1))
